[package]
authors.workspace = true
description = "Bitcoin authenticator for FRAME Contrib's pallet-pass: registers Bitcoin keys as devices and verifies their signed messages (BIP-137)."
edition.workspace = true
keywords = ["polkadot", "substrate", "bitcoin", "signature", "authentication"]
categories = ["authentication", "cryptography", "no-std"]
license.workspace = true
name = "pass-authenticators-bitcoin"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
codec.workspace = true
frame-support = { workspace = true, optional = true }
log.workspace = true
ripemd = { workspace = true, optional = true }
scale-info = { workspace = true, optional = true }
sp-core = { workspace = true, optional = true }
sp-io = { workspace = true, optional = true }
sp-runtime = { workspace = true, optional = true }
traits-authn.workspace = true

# Benchmarking
frame = { workspace = true, optional = true, features = ["runtime"] }
k256 = { workspace = true, optional = true, features = ["ecdsa"] }

[dev-dependencies]
frame = { workspace = true, features = ["runtime"] }
pallet-balances.workspace = true
pallet-pass.workspace = true
pallet-scheduler.workspace = true

[features]
default = ["std", "runtime", "full-crypto"]
runtime = [
  "dep:frame-support",
  "dep:ripemd",
  "dep:scale-info",
  "dep:sp-core",
  "dep:sp-io",
  "dep:sp-runtime",
  "traits-authn/runtime",
]
full-crypto = ["runtime", "sp-core/full_crypto"]
runtime-benchmarks = [
  "runtime",
  "dep:frame",
  "dep:k256",
  "frame/runtime-benchmarks",
  "frame-support?/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-pass/runtime-benchmarks",
  "pallet-scheduler/runtime-benchmarks",
  "sp-runtime?/runtime-benchmarks",
  "traits-authn/runtime-benchmarks",
]
std = [
  "codec/std",
  "frame-support?/std",
  "k256?/std",
  "frame/std",
  "log/std",
  "pallet-balances/std",
  "pallet-pass/std",
  "pallet-scheduler/std",
  "ripemd?/std",
  "scale-info?/std",
  "sp-core?/std",
  "sp-io?/std",
  "sp-runtime?/std",
  "traits-authn/std",
]
try-runtime = [
  "frame-support?/try-runtime",
  "pallet-pass/try-runtime",
  "pallet-balances/try-runtime",
  "pallet-scheduler/try-runtime",
  "frame/try-runtime",
  "sp-runtime?/try-runtime",
]
