[package]
name = "webauthn_verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coset = "0.3.8"
p256 = "0.13.2"
passkey = "0.3.0"
sha2 = "0.10.8"

[dev-dependencies]
rand = "0.8.5"