[package]
name = "webauthn_verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version="0.2.15", features = ["js"] }
p256 = {version = "0.13.2", features= ["digest", "ecdsa", "pem"]}
sha2 = "0.10.2"
